version: '3.8'
services:
  db:
    image: mysql
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: netology
    volumes:
      - ./docker/volumes/datadir:/var/lib/mysql mysql
    ports:
      - 3307:3306
  cloud_service:
    image: cloud_app
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080